
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abcd
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private Object frame1;

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student info");
        setLocation(new java.awt.Point(200, 200));
        setPreferredSize(new java.awt.Dimension(460, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("STUDENT INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 330, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 242));
        jLabel2.setText("Registration no.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 100, 210, 50);

        textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(textfield);
        textfield.setBounds(90, 150, 250, 40);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setText("Get details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 220, 100, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giphy (1).gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 470, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String txt=textfield.getText();
     if(txt.equals("316106715001"))
     {   
        NewJFrame01 f01=new NewJframe01();
        f01.setVisible(true);
        
     }
     else if(txt.equals("316106715002"))
      {
          NewJFrame02 f02=new NewJframe02();
          f02.setVisible(true);
      } 
     else if(txt.equals("316106715003"))
     {   
        NewJFrame03 f03=new NewJframe03();
        f03.setVisible(true);
        
     }
     else if(txt.equals("316106715004"))
     {   
        NewJFrame04 f04=new NewJframe04();
        f04.setVisible(true);
        
     }
        else if(txt.equals("316106715005"))
     {   
        NewJFrame05 f05=new NewJframe05();
        f05.setVisible(true);
        
     }
        else if(txt.equals("316106715006"))
     {   
        NewJFrame06 f06=new NewJframe06();
        f06.setVisible(true);
     }
        
     
        else  if(txt.equals("316106715007"))
     {   
        NewJFrame07 f07=new NewJframe07();
        f07.setVisible(true);
        
     }
        else if(txt.equals("316106715008"))
     {   
        NewJFrame08 f08=new NewJframe08();
        f08.setVisible(true);
        
     }
        else if(txt.equals("316106715009"))
     {   
        NewJFrame09 f09=new NewJframe09();
        f09.setVisible(true);
        
     }
        else  if(txt.equals("316106715010"))
     {   
        NewJFrame10 f10=new NewJframe10();
        f10.setVisible(true);
        
     }
        else if(txt.equals("316106715011"))
     {   
        NewJFrame11 f11=new NewJframe11();
        f11.setVisible(true);
        
     }
        else if(txt.equals("316106715012"))
     {   
        NewJFrame12 f12=new NewJframe12();
        f12.setVisible(true);
        
     }
        else if(txt.equals("316106715013"))
     {   
        NewJFrame13 f13=new NewJframe13();
        f13.setVisible(true);
        
     }
        else if(txt.equals("316106715014"))
     {   
        NewJFrame14 f14=new NewJframe14();
        f14.setVisible(true);
        
     }
        else if(txt.equals("316106715015"))
     {   
        NewJFrame15 f15=new NewJframe15();
        f15.setVisible(true);
        
     }
        else  if(txt.equals("316106715016"))
     {   
        NewJFrame16 f16=new NewJframe16();
        f16.setVisible(true);
        
     }
        else if(txt.equals("316106715017"))
     {   
        NewJFrame17 f17=new NewJframe17();
        f17.setVisible(true);
        
     }
        else if(txt.equals("316106715018"))
     {   
        NewJFrame18 f18=new NewJframe18();
        f18.setVisible(true);
        
     }
        else if(txt.equals("316106715019"))
     {   
        NewJFrame19 f19=new NewJframe19();
        f19.setVisible(true);
        
     }
        else if(txt.equals("316106715020"))
     {   
        NewJFrame20 f20=new NewJframe20();
        f20.setVisible(true);
        
     }
        else if(txt.equals("316106715021"))
     {   
        NewJFrame21 f21=new NewJframe21();
        f21.setVisible(true);
        
     }
        else if(txt.equals("316106715022"))
     {   
        NewJFrame22 f22=new NewJframe22();
        f22.setVisible(true);
        
     }
        else if(txt.equals("316106715023"))
     {   
        NewJFrame23 f23=new NewJframe23();
        f23.setVisible(true);
        
     }
 else if(txt.equals("316106715024"))
     {   
        NewJFrame24 f24=new NewJframe24();
        f24.setVisible(true);
        
     }
  else if(txt.equals("316106715025"))
     {   
        NewJFrame25 f25=new NewJframe25();
        f25.setVisible(true);
        
     }
else if(txt.equals("316106715026"))
     {   
        NewJFrame26 f26=new NewJframe26();
        f26.setVisible(true);
        
     }
else if(txt.equals("316106715027"))
     {   
        NewJFrame27 f27=new NewJframe27();
        f27.setVisible(true);
        
     }
 else 
 {
     JOptionPane.showMessageDialog(null, "invalid registration no.");
           textfield.setText(null);
           
 }










   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER)
      {
             String txt=textfield.getText();
     if (txt.equals("316106715001"))
     {   
        NewJFrame01 f01=new NewJframe01();
        f01.setVisible(true);
        
     }
     else if(txt.equals("316106715002"))
      {
          NewJFrame02 f02=new NewJframe02();
          f02.setVisible(true);
      } 
     else if(txt.equals("316106715003"))
     {   
        NewJFrame03 f03=new NewJframe03();
        f03.setVisible(true);
        
     }
     else if(txt.equals("316106715004"))
     {   
        NewJFrame04 f04=new NewJframe04();
        f04.setVisible(true);
        
     }
        else if(txt.equals("316106715005"))
     {   
        NewJFrame05 f05=new NewJframe05();
        f05.setVisible(true);
        
     }
        else if(txt.equals("316106715006"))
     {   
        NewJFrame06 f06=new NewJframe06();
        f06.setVisible(true);
     }
        
     
        else  if(txt.equals("316106715007"))
     {   
        NewJFrame07 f07=new NewJframe07();
        f07.setVisible(true);
        
     }
        else if(txt.equals("316106715008"))
     {   
        NewJFrame08 f08=new NewJframe08();
        f08.setVisible(true);
        
     }
        else if(txt.equals("316106715009"))
     {   
        NewJFrame09 f09=new NewJframe09();
        f09.setVisible(true);
        
     }
        else  if(txt.equals("316106715010"))
     {   
        NewJFrame10 f10=new NewJframe10();
        f10.setVisible(true);
        
     }
        else if(txt.equals("316106715011"))
     {   
        NewJFrame11 f11=new NewJframe11();
        f11.setVisible(true);
        
     }
        else if(txt.equals("316106715012"))
     {   
        NewJFrame12 f12=new NewJframe12();
        f12.setVisible(true);
        
     }
        else if(txt.equals("316106715013"))
     {   
        NewJFrame13 f13=new NewJframe13();
        f13.setVisible(true);
        
     }
        else if(txt.equals("316106715014"))
     {   
        NewJFrame14 f14=new NewJframe14();
        f14.setVisible(true);
        
     }
        else if(txt.equals("316106715015"))
     {   
        NewJFrame15 f15=new NewJframe15();
        f15.setVisible(true);
        
     }
        else  if(txt.equals("316106715016"))
     {   
        NewJFrame16 f16=new NewJframe16();
        f16.setVisible(true);
        
     }
        else if(txt.equals("316106715017"))
     {   
        NewJFrame17 f17=new NewJframe17();
        f17.setVisible(true);
        
     }
        else if(txt.equals("316106715018"))
     {   
        NewJFrame18 f18=new NewJframe18();
        f18.setVisible(true);
        
     }
        else if(txt.equals("316106715019"))
     {   
        NewJFrame19 f19=new NewJframe19();
        f19.setVisible(true);
        
     }
        else if(txt.equals("316106715020"))
     {   
        NewJFrame20 f20=new NewJframe20();
        f20.setVisible(true);
        
     }
        else if(txt.equals("316106715021"))
     {   
        NewJFrame21 f21=new NewJframe21();
        f21.setVisible(true);
        
     }
        else if(txt.equals("316106715022"))
     {   
        NewJFrame22 f22=new NewJframe22();
        f22.setVisible(true);
        
     }
        else if(txt.equals("316106715023"))
     {   
        NewJFrame23 f23=new NewJframe23();
        f23.setVisible(true);
        
     }
 else if(txt.equals("316106715024"))
     {   
        NewJFrame24 f24=new NewJframe24();
        f24.setVisible(true);
        
     }
  else if(txt.equals("316106715025"))
     {   
        NewJFrame25 f25=new NewJframe25();
        f25.setVisible(true);
        
     }
else if(txt.equals("316106715026"))
     {   
        NewJFrame26 f26=new NewJframe26();
        f26.setVisible(true);
        
     }
else if(txt.equals("316106715027"))
     {   
        NewJFrame27 f27=new NewJframe27();
        f27.setVisible(true);
        
     }
 else 
 {
     JOptionPane.showMessageDialog(null, "invalid registration no.");
           textfield.setText(null);
           
 }


      }
          
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textfield;
    // End of variables declaration//GEN-END:variables

    private static class NewJframe01 extends NewJFrame01 {

        public NewJframe01() {
        }
    }

    private static class NewJframe02 extends NewJFrame02 {

        public NewJframe02() {
        }
    }

    private static class NewJframe27 extends NewJFrame27 {

        public NewJframe27() {
        }
    }

    private static class NewJframe03 extends NewJFrame03 {

        public NewJframe03() {
        }
    }

    private static class NewJframe04 extends NewJFrame04 {

        public NewJframe04() {
        }
    }

    private static class NewJframe05 extends NewJFrame05 {

        public NewJframe05() {
        }
    }

    private static class NewJframe06 extends NewJFrame06 {

        public NewJframe06() {
        }
    }

    private static class NewJframe07 extends NewJFrame07 {

        public NewJframe07() {
        }
    }

    private static class NewJframe08 extends NewJFrame08 {

        public NewJframe08() {
        }
    }

    private static class NewJframe09 extends NewJFrame09 {

        public NewJframe09() {
        }
    }

    private static class NewJframe10 extends NewJFrame10 {

        public NewJframe10() {
        }
    }

    private static class NewJframe11 extends NewJFrame11 {

        public NewJframe11() {
        }
    }

    private static class NewJframe12 extends NewJFrame12 {

        public NewJframe12() {
        }
    }

    private static class NewJframe13 extends NewJFrame13 {

        public NewJframe13() {
        }
    }

    private static class NewJframe14 extends NewJFrame14 {

        public NewJframe14() {
        }
    }

    private static class NewJframe15 extends NewJFrame15 {

        public NewJframe15() {
        }
    }

    private static class NewJframe16 extends NewJFrame16 {

        public NewJframe16() {
        }
    }

    private static class NewJframe17 extends NewJFrame17 {

        public NewJframe17() {
        }
    }

    private static class NewJframe18 extends NewJFrame18 {

        public NewJframe18() {
        }
    }

    private static class NewJframe19 extends NewJFrame19 {

        public NewJframe19() {
        }
    }

    private static class NewJframe20 extends NewJFrame20 {

        public NewJframe20() {
        }
    }

    private static class NewJframe21 extends NewJFrame21 {

        public NewJframe21() {
        }
    }

    private static class NewJframe22 extends NewJFrame22 {

        public NewJframe22() {
        }
    }

    private static class NewJframe23 extends NewJFrame23 {

        public NewJframe23() {
        }
    }

    private static class NewJframe24 extends NewJFrame24 {

        public NewJframe24() {
        }
    }

    private static class NewJframe25 extends NewJFrame25 {

        public NewJframe25() {
        }
    }

    private static class NewJframe26 extends NewJFrame26 {

        public NewJframe26() {
        }
    }

}
